### ISSUE TITLE
MuTect: Pileup Element cannot create a deletion with a negative offset

### ISSUE THREAD

**Issue by kcibul** [broadinstitute/mutect#1]
A collaborator has seen this issue on some externally aligned data

```
org.broadinstitute.sting.utils.exceptions.ReviewedStingException: Pileup Element cannot create a deletion with a negative offset
at org.broadinstitute.sting.utils.pileup.PileupElement.<init>(PileupElement.java:41)
at org.broadinstitute.sting.gatk.iterators.LocusIteratorByState.lazyLoadNextAlignmentContext(LocusIteratorByState.java:470)
at org.broadinstitute.sting.gatk.iterators.LocusIteratorByState.hasNext(LocusIteratorByState.java:332)
at net.sf.picard.util.PeekableIterator.advance(PeekableIterator.java:70)
at net.sf.picard.util.PeekableIterator.next(PeekableIterator.java:57)
at org.broadinstitute.sting.gatk.executive.WindowMaker$WindowMakerIterator.advance(WindowMaker.java:156)
at org.broadinstitute.sting.gatk.executive.WindowMaker$WindowMakerIterator.hasNext(WindowMaker.java:125)
at org.broadinstitute.sting.gatk.datasources.providers.LocusView.advance(LocusView.java:151)
at org.broadinstitute.sting.gatk.datasources.providers.LocusView.hasNextLocus(LocusView.java:117)
at org.broadinstitute.sting.gatk.datasources.providers.AllLocusView.advance(AllLocusView.java:102)
at org.broadinstitute.sting.gatk.datasources.providers.AllLocusView.hasNext(AllLocusView.java:60)
at org.broadinstitute.sting.gatk.traversals.TraverseLoci.traverse(TraverseLoci.java:50)
at org.broadinstitute.sting.gatk.traversals.TraverseLoci.traverse(TraverseLoci.java:18)
at org.broadinstitute.sting.gatk.executive.LinearMicroScheduler.execute(LinearMicroScheduler.java:63)
at org.broadinstitute.sting.gatk.GenomeAnalysisEngine.execute(GenomeAnalysisEngine.java:233)
at org.broadinstitute.sting.gatk.CommandLineExecutable.execute(CommandLineExecutable.java:122)
at org.broadinstitute.sting.commandline.CommandLineProgram.start(CommandLineProgram.java:236)
at org.broadinstitute.sting.commandline.CommandLineProgram.start(CommandLineProgram.java:146)
at org.broadinstitute.sting.gatk.CommandLineGATK.main(CommandLineGATK.java:92)
```

**Comment by kcibul** [comment]
Reproduced under mutect_support/git-001

Caused by bad read alignments (invalid BAM file).  These bad BAMs can still be called by using "-rf BadCigar" (GATK feature)
